### ISSUE TITLE
Add support to pack forge

### ISSUE THREAD

**Issue by Indemnity83** [Indemnity83/Solder-Toolbelt#5]
Attempting to 'mod pack' forge (or other core mods) will fail because there is no modinfo file. Also the structure of the packed zip is different than a nomad mod

**Comment by EntranceJew** [comment]
The way I see this working is basically doing the same set of things that the packMod function does, but probing for a different file (MinecraftForge-license.txt?) and then changing the target folder to pack the config to and what to name it.

If that solution seems good enough then I can start working on this.

**Comment by Indemnity83** [comment]
That's basically all I was after. Just put it in as an issue so I wouldn't lose track of it.
