### ISSUE TITLE
Init command fails on case-sensitive filesystem.

### ISSUE THREAD

**Issue by EntranceJew** [Indemnity83/Solder-Toolbelt#6]
I started working on a fix for this about an hour ago but [I lack the git-fu to work around the changes made in the last hour](https://github.com/EntranceJew/SolderToolbelt/tree/bugfix-config-wrong-path).

Lesson learned: create issues early, create issues often.

**Comment by Indemnity83** [comment]
Sorry about that, it needed to happen though, the master branch was a mess of working and non-working code. 

The way to fix it is to [sync your fork](https://help.github.com/articles/syncing-a-fork/) then create a new branch based on develop and cherry-pick the changes into that, then force push that new branch over the origin one. There is a chance you'll have to deal with some merge conflicts when you do the cherry picks, if that happens fix it and then issue a 'git cherry-pick --continue' to finish the pick

[get your forks develop synced first]
git checkout develop
git -m bugfix-config-wrong-path bugfix-config-wrong-path-old
git branch bugfix-config-wrong-path
git checkout bugfix-config-wrong-path
git cherry-pick 18a0016
git cherry-pick 025f283
git cherry-pick cbb802c
git push -f origin/bugfix-config-wrong-path

Alternatively, if you want, I'll just cherry-pick the commits manually, but then you won't get any credit for the commits.

**Comment by EntranceJew** [comment]
Got it, thanks!
I was in the process of rebasing but it was looking murky.

**Comment by Indemnity83** [comment]
Merged your PR, thanks!
